# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choise',
            old_name='qustion',
            new_name='question',
        ),
    ]
